source 'https://rubygems.org'

gem "cucumber", "~> 1.3.0" 
gem "calabash-common", "~> 0.0.1" 
gem "json"
gem 'edn'
gem "CFPropertyList"
gem "sim_launcher", "0.4.6"
gem "slowhandcuke" 
gem "location-one", "~>0.0.10"
gem "httpclient","~> 2.3.3"
gem "bundler", "~> 1.1"
gem "run_loop", "~> 0.0.21" 
gem "awesome_print"
gem "xamarin-test-cloud", "~> 0.9.25"



# gem 'briar', :github => 'jmoody/briar', :branch => '0.0.9'
# gem 'calabash-cucumber', :github => 'jmoody/calabash-ios', :branch => '0.9.x-riseup-branch'
# gem 'calabash-android'
